// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Yarito.Infra.Database.SQLServer.Identity.DatabaseContext;

#nullable disable

namespace Yarito.Infra.Database.SQLServer.Identity.Migrations
{
    [DbContext(typeof(IdentityAppDbContext))]
    [Migration("20251225192920_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("identity")
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", "identity");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConcurrencyStamp = "A1B2C3D4-E5F6-4789-A1B2-C3D4E5F6A7B8",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = 2,
                            ConcurrencyStamp = "B2C3D4E5-F6A7-4890-B2C3-D4E5F6A7B8C9",
                            Name = "Customer",
                            NormalizedName = "CUSTOMER"
                        },
                        new
                        {
                            Id = 3,
                            ConcurrencyStamp = "C3D4E5F6-A7B8-4901-C3D4-E5F6A7B8C9D0",
                            Name = "Expert",
                            NormalizedName = "EXPERT"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", "identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", "identity");

                    b.HasData(
                        new
                        {
                            Id = 11,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "K1L2M3N4-O5P6-Q7R8-S9T0-U1V2W3X4Y5Z6",
                            Email = "admin@yarito.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@YARITO.COM",
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAIAAYagAAAAEHhN/j3HYyaZzYYPHenA6ah4LqHavRvRSgoDkoroEeUwmQXnuJjPG+tOdsXVS5IclQ==",
                            PhoneNumber = "09991234567",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "1K2L3M4N5O6P7Q8R9S0T",
                            TwoFactorEnabled = false,
                            UserName = "admin"
                        },
                        new
                        {
                            Id = 1,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "A1B2C3D4-E5F6-G7H8-I9J0-K1L2M3N4O5P6",
                            Email = "ali.mohammadi@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ALI.MOHAMMADI@EXAMPLE.COM",
                            NormalizedUserName = "09121234567",
                            PasswordHash = "AQAAAAIAAYagAAAAEGnOQvwOcxEf8JN1dyn0DcnzOzGCHTej4fE1KTLW0iht3rh0Ic12qEiR3vSOR5X6iA==",
                            PhoneNumber = "09121234567",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "1A2B3C4D5E6F7G8H9I0J",
                            TwoFactorEnabled = false,
                            UserName = "09121234567"
                        },
                        new
                        {
                            Id = 2,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "B2C3D4E5-F6G7-H8I9-J0K1-L2M3N4O5P6Q7",
                            Email = "zahra.ahmadi@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ZAHRA.AHMADI@EXAMPLE.COM",
                            NormalizedUserName = "09131234567",
                            PasswordHash = "AQAAAAIAAYagAAAAEL0SVuaghfh5hsSVQI/T5k14bnaWpD+9E8b3HZU6NVNehFIrlT6HFIz4YTanejzIDA==",
                            PhoneNumber = "09131234567",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "2B3C4D5E6F7G8H9I0J1K",
                            TwoFactorEnabled = false,
                            UserName = "09131234567"
                        },
                        new
                        {
                            Id = 3,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "C3D4E5F6-G7H8-I9J0-K1L2-M3N4O5P6Q7R8",
                            Email = "mohammad.rezaei@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "MOHAMMAD.REZAEI@EXAMPLE.COM",
                            NormalizedUserName = "09141234567",
                            PasswordHash = "AQAAAAIAAYagAAAAECDijNSiz2w+vqyQgRvbv1EnmMU5nsnLXE/TINpKadS37imVYsw7zIgIbUdjBYUXmg==",
                            PhoneNumber = "09141234567",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "3C4D5E6F7G8H9I0J1K2L",
                            TwoFactorEnabled = false,
                            UserName = "09141234567"
                        },
                        new
                        {
                            Id = 4,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "D4E5F6G7-H8I9-J0K1-L2M3-N4O5P6Q7R8S9",
                            Email = "fatemeh.hosseini@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "FATEMEH.HOSSEINI@EXAMPLE.COM",
                            NormalizedUserName = "09151234567",
                            PasswordHash = "AQAAAAIAAYagAAAAEGfNyghhaEYd/XZPYR4V5khU5stRk2LLmqBLosBvnXBMaNFOHiJX9yZBkaA7kgdSaw==",
                            PhoneNumber = "09151234567",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "4D5E6F7G8H9I0J1K2L3M",
                            TwoFactorEnabled = false,
                            UserName = "09151234567"
                        },
                        new
                        {
                            Id = 5,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "E5F6G7H8-I9J0-K1L2-M3N4-O5P6Q7R8S9T0",
                            Email = "hossein.karimi@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "HOSSEIN.KARIMI@EXAMPLE.COM",
                            NormalizedUserName = "09161234567",
                            PasswordHash = "AQAAAAIAAYagAAAAEJnUfzORLHnWiZ275waK8BfN6PQc9yHmV4DaMoSyj71we3HGg4fLlum4pSJ+2P6hGw==",
                            PhoneNumber = "09161234567",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "5E6F7G8H9I0J1K2L3M4N",
                            TwoFactorEnabled = false,
                            UserName = "09161234567"
                        },
                        new
                        {
                            Id = 6,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "F6G7H8I9-J0K1-L2M3-N4O5-P6Q7R8S9T0U1",
                            Email = "reza.bargkar@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "REZA.BARGKAR@EXAMPLE.COM",
                            NormalizedUserName = "09171234567",
                            PasswordHash = "AQAAAAIAAYagAAAAEONrjpAbgA6cYOdlRyrSE4QbihOpWoYcTBdL5dcdveG5Ve13xtON20agoVZzh4IKsg==",
                            PhoneNumber = "09171234567",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "6F7G8H9I0J1K2L3M4N5O",
                            TwoFactorEnabled = false,
                            UserName = "09171234567"
                        },
                        new
                        {
                            Id = 7,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "G7H8I9J0-K1L2-M3N4-O5P6-Q7R8S9T0U1V2",
                            Email = "mehdi.loolehkesh@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "MEHDI.LOOLEHKESH@EXAMPLE.COM",
                            NormalizedUserName = "09181234567",
                            PasswordHash = "AQAAAAIAAYagAAAAEEl7NXT3vAZoJKbL5Kcon5mEGpTT1D4gHiQ5xkdOHCC2D4CjSfgb7HP5FTfvblV7aQ==",
                            PhoneNumber = "09181234567",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "7G8H9I0J1K2L3M4N5O6P",
                            TwoFactorEnabled = false,
                            UserName = "09181234567"
                        },
                        new
                        {
                            Id = 8,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "H8I9J0K1-L2M3-N4O5-P6Q7-R8S9T0U1V2W3",
                            Email = "sara.nezafatchi@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "SARA.NEZAFATCHI@EXAMPLE.COM",
                            NormalizedUserName = "09191234567",
                            PasswordHash = "AQAAAAIAAYagAAAAEHDewutS4HMeCo5VWBTfWhHE8YtHwdUxTFZpVbxPQqlpnnV13V9PsUCLh5ND58qygw==",
                            PhoneNumber = "09191234567",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "8H9I0J1K2L3M4N5O6P7Q",
                            TwoFactorEnabled = false,
                            UserName = "09191234567"
                        },
                        new
                        {
                            Id = 9,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "I9J0K1L2-M3N4-O5P6-Q7R8-S9T0U1V2W3X4",
                            Email = "ahmad.naghash@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "AHMAD.NAGHASH@EXAMPLE.COM",
                            NormalizedUserName = "09201234567",
                            PasswordHash = "AQAAAAIAAYagAAAAEKTu/sQhqXfPI8zqrj64y6Kd6qF+AfGFUvzsU0xiDLyVZsqg6+qzeKxuoT4GBKUg3A==",
                            PhoneNumber = "09201234567",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "9I0J1K2L3M4N5O6P7Q8R",
                            TwoFactorEnabled = false,
                            UserName = "09201234567"
                        },
                        new
                        {
                            Id = 10,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "J0K1L2M3-N4O5-P6Q7-R8S9-T0U1V2W3X4Y5",
                            Email = "narges.tamirkar@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "NARGES.TAMIRKAR@EXAMPLE.COM",
                            NormalizedUserName = "09211234567",
                            PasswordHash = "AQAAAAIAAYagAAAAEIO/f+DZhUb3O35lY6n10pxWHuGm0wSQIfxKmTmtVdceBBWK9HfRt0azRZ/dRwG9Zg==",
                            PhoneNumber = "09211234567",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "0J1K2L3M4N5O6P7Q8R9S",
                            TwoFactorEnabled = false,
                            UserName = "09211234567"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", "identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", "identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", "identity");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 2,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 3,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 4,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 5,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 6,
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 7,
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 8,
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 9,
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 10,
                            RoleId = 3
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", "identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser<int>", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser<int>", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser<int>", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser<int>", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
