<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Contracts\Images\AppServices\" />
    <Folder Include="Contracts\Images\Repository\" />
    <Folder Include="Contracts\Images\Services\" />
    <Folder Include="Contracts\_Common\AppServices\" />
    <Folder Include="DTOs\Images\" />
  </ItemGroup>

</Project>
