<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation" Version="10.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Yarito.Domain.AppServices\Yarito.Domain.AppServices.csproj" />
    <ProjectReference Include="..\Yarito.Domain.Core\Yarito.Domain.Core.csproj" />
    <ProjectReference Include="..\Yarito.Domain.Services\Yarito.Domain.Services.csproj" />
    <ProjectReference Include="..\Yarito.Infra.DataAccess.EFCore\Yarito.Infra.DataAccess.EFCore.csproj" />
    <ProjectReference Include="..\Yarito.Infra.Database.SQLServer.EFCore\Yarito.Infra.Database.SQLServer.EFCore.csproj" />
  </ItemGroup>

</Project>
