// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Yarito.Infra.Database.SQLServer.EFCore.DatabaseContext;

#nullable disable

namespace Yarito.Infra.Database.SQLServer.EFCore.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251230133957_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ExpertWork", b =>
                {
                    b.Property<int>("ExpertsId")
                        .HasColumnType("int");

                    b.Property<int>("WorksId")
                        .HasColumnType("int");

                    b.HasKey("ExpertsId", "WorksId");

                    b.HasIndex("WorksId");

                    b.ToTable("ExpertWorks", (string)null);

                    b.HasData(
                        new
                        {
                            ExpertsId = 6,
                            WorksId = 1
                        },
                        new
                        {
                            ExpertsId = 6,
                            WorksId = 2
                        },
                        new
                        {
                            ExpertsId = 6,
                            WorksId = 3
                        },
                        new
                        {
                            ExpertsId = 7,
                            WorksId = 4
                        },
                        new
                        {
                            ExpertsId = 7,
                            WorksId = 5
                        },
                        new
                        {
                            ExpertsId = 7,
                            WorksId = 6
                        },
                        new
                        {
                            ExpertsId = 8,
                            WorksId = 7
                        },
                        new
                        {
                            ExpertsId = 8,
                            WorksId = 8
                        },
                        new
                        {
                            ExpertsId = 8,
                            WorksId = 9
                        },
                        new
                        {
                            ExpertsId = 9,
                            WorksId = 10
                        },
                        new
                        {
                            ExpertsId = 9,
                            WorksId = 11
                        },
                        new
                        {
                            ExpertsId = 9,
                            WorksId = 12
                        },
                        new
                        {
                            ExpertsId = 10,
                            WorksId = 13
                        },
                        new
                        {
                            ExpertsId = 10,
                            WorksId = 14
                        },
                        new
                        {
                            ExpertsId = 10,
                            WorksId = 15
                        },
                        new
                        {
                            ExpertsId = 10,
                            WorksId = 2
                        });
                });

            modelBuilder.Entity("Yarito.Domain.Core.Entities.Cities.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 12, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Name = "تهران"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 12, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Name = "اصفهان"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 12, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Name = "فارس"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 12, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Name = "تهران",
                            ParentId = 1
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 12, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Name = "کرج",
                            ParentId = 1
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 12, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Name = "ری",
                            ParentId = 1
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2025, 12, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Name = "اصفهان",
                            ParentId = 2
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2025, 12, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Name = "نجف‌آباد",
                            ParentId = 2
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2025, 12, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Name = "کاشان",
                            ParentId = 2
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2025, 12, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Name = "شیراز",
                            ParentId = 3
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2025, 12, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Name = "مرودشت",
                            ParentId = 3
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2025, 12, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Name = "جهرم",
                            ParentId = 3
                        });
                });

            modelBuilder.Entity("Yarito.Domain.Core.Entities.Images.RequestImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImgPath")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("RequestId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RequestId");

                    b.ToTable("RequestImages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 11, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImgPath = "/images/requests/req1_img1_a7f3d8e2.jpg",
                            IsDeleted = false,
                            RequestId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 11, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImgPath = "/images/requests/req1_img2_b4e9c1f6.jpg",
                            IsDeleted = false,
                            RequestId = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 12, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImgPath = "/images/requests/req2_img1_c2d8a5b9.jpg",
                            IsDeleted = false,
                            RequestId = 2
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 12, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImgPath = "/images/requests/req3_img1_d9f6e3c7.jpg",
                            IsDeleted = false,
                            RequestId = 3
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 12, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImgPath = "/images/requests/req3_img2_e5a8b4d1.jpg",
                            IsDeleted = false,
                            RequestId = 3
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 12, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImgPath = "/images/requests/req3_img3_f1c9d7e2.jpg",
                            IsDeleted = false,
                            RequestId = 3
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2025, 12, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImgPath = "/images/requests/req4_img1_g8b5f2a6.jpg",
                            IsDeleted = false,
                            RequestId = 4
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2025, 12, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImgPath = "/images/requests/req4_img2_h3d7c9e4.jpg",
                            IsDeleted = false,
                            RequestId = 4
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2025, 12, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImgPath = "/images/requests/req5_img1_i6e2a8b5.jpg",
                            IsDeleted = false,
                            RequestId = 5
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2025, 12, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImgPath = "/images/requests/req6_img1_j9f4c3d7.jpg",
                            IsDeleted = false,
                            RequestId = 6
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2025, 12, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImgPath = "/images/requests/req6_img2_k2a5e8b1.jpg",
                            IsDeleted = false,
                            RequestId = 6
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2025, 12, 24, 12, 0, 0, 0, DateTimeKind.Utc),
                            ImgPath = "/images/requests/req7_img1_l7c9d2f6.jpg",
                            IsDeleted = false,
                            RequestId = 7
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2025, 12, 24, 16, 0, 0, 0, DateTimeKind.Utc),
                            ImgPath = "/images/requests/req8_img1_m4e6a3b8.jpg",
                            IsDeleted = false,
                            RequestId = 8
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2025, 12, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImgPath = "/images/requests/req10_img1_n8f5d7c2.jpg",
                            IsDeleted = false,
                            RequestId = 10
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2025, 12, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImgPath = "/images/requests/req10_img2_o1b9e4a6.jpg",
                            IsDeleted = false,
                            RequestId = 10
                        });
                });

            modelBuilder.Entity("Yarito.Domain.Core.Entities.Requests.Bid", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("ExpertId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal>("ProposedPrice")
                        .HasColumnType("decimal(18,0)");

                    b.Property<DateTime>("ProposedVisitDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("RequestId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("ExpertId");

                    b.HasIndex("RequestId", "ExpertId")
                        .IsUnique();

                    b.ToTable("Bids");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "سلام، تجربه 10 ساله در سیم‌کشی دارم. کار رو با کیفیت عالی انجام میدم.",
                            ExpertId = 6,
                            IsDeleted = false,
                            ProposedPrice = 2300000m,
                            ProposedVisitDateTime = new DateTime(2025, 12, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            RequestId = 1,
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "آماده انجام کار هستم با قیمت مناسب",
                            ExpertId = 10,
                            IsDeleted = false,
                            ProposedPrice = 2600000m,
                            ProposedVisitDateTime = new DateTime(2025, 12, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            RequestId = 1,
                            Status = 2
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 12, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "متخصص لوله کشی با 8 سال سابقه، همراه با گارانتی",
                            ExpertId = 7,
                            IsDeleted = false,
                            ProposedPrice = 480000m,
                            ProposedVisitDateTime = new DateTime(2025, 12, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            RequestId = 2,
                            Status = 1
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 12, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "با ضمانت کیفیت و قیمت عالی",
                            ExpertId = 8,
                            IsDeleted = false,
                            ProposedPrice = 1750000m,
                            ProposedVisitDateTime = new DateTime(2025, 12, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            RequestId = 3,
                            Status = 1
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 12, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "نقاش حرفه‌ای با سابقه کار روی پروژه‌های بزرگ",
                            ExpertId = 9,
                            IsDeleted = false,
                            ProposedPrice = 3800000m,
                            ProposedVisitDateTime = new DateTime(2025, 12, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            RequestId = 4,
                            Status = 2
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 12, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "تعمیر فوری یخچال با بهترین قیمت",
                            ExpertId = 10,
                            IsDeleted = false,
                            ProposedPrice = 1400000m,
                            ProposedVisitDateTime = new DateTime(2025, 12, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            RequestId = 5,
                            Status = 1
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2025, 12, 24, 4, 0, 0, 0, DateTimeKind.Utc),
                            Description = "نصب لوستر با تجربه بالا",
                            ExpertId = 6,
                            IsDeleted = false,
                            ProposedPrice = 550000m,
                            ProposedVisitDateTime = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            RequestId = 6,
                            Status = 0
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2025, 12, 24, 6, 0, 0, 0, DateTimeKind.Utc),
                            Description = "آماده نصب در کمترین زمان",
                            ExpertId = 10,
                            IsDeleted = false,
                            ProposedPrice = 650000m,
                            ProposedVisitDateTime = new DateTime(2026, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            RequestId = 6,
                            Status = 0
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2025, 12, 24, 14, 0, 0, 0, DateTimeKind.Utc),
                            Description = "قالیشویی با دستگاه‌های مدرن",
                            ExpertId = 8,
                            IsDeleted = false,
                            ProposedPrice = 2800000m,
                            ProposedVisitDateTime = new DateTime(2026, 1, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            RequestId = 7,
                            Status = 0
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2025, 12, 24, 18, 0, 0, 0, DateTimeKind.Utc),
                            Description = "تعمیر فوری توالت فرنگی",
                            ExpertId = 7,
                            IsDeleted = false,
                            ProposedPrice = 650000m,
                            ProposedVisitDateTime = new DateTime(2025, 12, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            RequestId = 8,
                            Status = 0
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2025, 12, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "تعمیر ماشین لباسشویی با گارانتی کامل",
                            ExpertId = 10,
                            IsDeleted = false,
                            ProposedPrice = 1150000m,
                            ProposedVisitDateTime = new DateTime(2025, 12, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            RequestId = 10,
                            Status = 1
                        });
                });

            modelBuilder.Entity("Yarito.Domain.Core.Entities.Requests.Request", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AcceptedBidId")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("PreferredVisitDateTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("ProposedPrice")
                        .HasColumnType("decimal(18,0)");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("WorkId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AcceptedBidId")
                        .IsUnique()
                        .HasFilter("[AcceptedBidId] IS NOT NULL");

                    b.HasIndex("CustomerId");

                    b.HasIndex("WorkId");

                    b.ToTable("Requests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "تهران، خیابان ولیعصر، پلاک 123، واحد 5",
                            CreatedAt = new DateTime(2025, 11, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = 1,
                            Description = "نیاز به سیم‌کشی کامل آشپزخانه برای نصب هود و کابینت",
                            IsDeleted = false,
                            PreferredVisitDateTime = new DateTime(2025, 12, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProposedPrice = 2500000m,
                            Status = 2,
                            Title = "سیم‌کشی آشپزخانه",
                            WorkId = 1
                        },
                        new
                        {
                            Id = 2,
                            Address = "اصفهان، خیابان چهارباغ، پلاک 45، طبقه سوم",
                            CreatedAt = new DateTime(2025, 12, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = 2,
                            Description = "شیر آب آشپزخانه نشتی دارد و نیاز به تعویض دارد",
                            IsDeleted = false,
                            PreferredVisitDateTime = new DateTime(2025, 12, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProposedPrice = 500000m,
                            Status = 2,
                            Title = "تعمیر شیر آب آشپزخانه",
                            WorkId = 5
                        },
                        new
                        {
                            Id = 3,
                            Address = "شیراز، خیابان زند، پلاک 78، واحد 12",
                            CreatedAt = new DateTime(2025, 12, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = 3,
                            Description = "نظافت کامل منزل 120 متری قبل از نوروز",
                            IsDeleted = false,
                            PreferredVisitDateTime = new DateTime(2025, 12, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProposedPrice = 1800000m,
                            Status = 2,
                            Title = "نظافت کامل منزل",
                            WorkId = 7
                        },
                        new
                        {
                            Id = 4,
                            Address = "کرج، میدان آزادگان، پلاک 56، واحد 8",
                            CreatedAt = new DateTime(2025, 12, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = 4,
                            Description = "نقاشی و رنگ‌آمیزی دو اتاق خواب",
                            IsDeleted = false,
                            PreferredVisitDateTime = new DateTime(2025, 12, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProposedPrice = 3500000m,
                            Status = 1,
                            Title = "رنگ اتاق خواب",
                            WorkId = 10
                        },
                        new
                        {
                            Id = 5,
                            Address = "کاشان، خیابان کمال الملک، پلاک 90، طبقه دوم",
                            CreatedAt = new DateTime(2025, 12, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = 5,
                            Description = "یخچال یخ نمی‌زند و نیاز به بررسی دارد",
                            IsDeleted = false,
                            PreferredVisitDateTime = new DateTime(2025, 12, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProposedPrice = 1500000m,
                            Status = 1,
                            Title = "تعمیر یخچال سامسونگ",
                            WorkId = 14
                        },
                        new
                        {
                            Id = 6,
                            Address = "تهران، خیابان انقلاب، پلاک 200، واحد 3",
                            CreatedAt = new DateTime(2025, 12, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = 1,
                            Description = "نصب یک لوستر سنگین در سالن پذیرایی",
                            IsDeleted = false,
                            PreferredVisitDateTime = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProposedPrice = 600000m,
                            Status = 0,
                            Title = "نصب لوستر سالن",
                            WorkId = 2
                        },
                        new
                        {
                            Id = 7,
                            Address = "اصفهان، خیابان سپاهان، پلاک 150، واحد 6",
                            CreatedAt = new DateTime(2025, 12, 24, 12, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = 2,
                            Description = "قالیشویی یک فرش دستباف 12 متری",
                            IsDeleted = false,
                            PreferredVisitDateTime = new DateTime(2026, 1, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProposedPrice = 3000000m,
                            Status = 0,
                            Title = "شستشوی فرش ایرانی",
                            WorkId = 9
                        },
                        new
                        {
                            Id = 8,
                            Address = "شیراز، خیابان مطهری، پلاک 85، طبقه اول",
                            CreatedAt = new DateTime(2025, 12, 24, 16, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = 3,
                            Description = "توالت فرنگی به درستی آب نمی‌کشد",
                            IsDeleted = false,
                            PreferredVisitDateTime = new DateTime(2025, 12, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProposedPrice = 700000m,
                            Status = 0,
                            Title = "تعمیر توالت فرنگی",
                            WorkId = 6
                        },
                        new
                        {
                            Id = 9,
                            Address = "کرج، خیابان فردوسی، پلاک 320",
                            CreatedAt = new DateTime(2025, 12, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = 4,
                            Description = "رنگ‌آمیزی نمای یک ساختمان سه طبقه",
                            IsDeleted = false,
                            PreferredVisitDateTime = new DateTime(2025, 12, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProposedPrice = 8000000m,
                            Status = 3,
                            Title = "نقاشی نمای ساختمان",
                            WorkId = 11
                        },
                        new
                        {
                            Id = 10,
                            Address = "تهران، خیابان آزادی، پلاک 450، واحد 15",
                            CreatedAt = new DateTime(2025, 12, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = 5,
                            Description = "ماشین لباسشویی در حین کار خاموش می‌شود",
                            IsDeleted = false,
                            PreferredVisitDateTime = new DateTime(2025, 12, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProposedPrice = 1200000m,
                            Status = 2,
                            Title = "تعمیر ماشین لباسشویی",
                            WorkId = 13
                        });
                });

            modelBuilder.Entity("Yarito.Domain.Core.Entities.Requests.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("ExpertId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<int>("RequestId")
                        .HasColumnType("int");

                    b.Property<int>("ReviewStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ExpertId");

                    b.HasIndex("RequestId")
                        .IsUnique();

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Comment = "کار بسیار عالی و حرفه‌ای انجام شد. آقای برقکار بسیار دقیق و وقت‌شناس بودند. پیشنهاد می‌کنم.",
                            CreatedAt = new DateTime(2025, 12, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = 1,
                            ExpertId = 6,
                            IsDeleted = false,
                            Rating = 5,
                            RequestId = 1,
                            ReviewStatus = 1
                        },
                        new
                        {
                            Id = 2,
                            Comment = "کار خوبی انجام شد. فقط کمی دیرتر از موعد مقرر آمدند.",
                            CreatedAt = new DateTime(2025, 12, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = 2,
                            ExpertId = 7,
                            IsDeleted = false,
                            Rating = 4,
                            RequestId = 2,
                            ReviewStatus = 1
                        },
                        new
                        {
                            Id = 3,
                            Comment = "نظافت فوق‌العاده دقیق و تمیز. خانم نظافتچی بسیار محترم و مودب بودند.",
                            CreatedAt = new DateTime(2025, 12, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = 3,
                            ExpertId = 8,
                            IsDeleted = false,
                            Rating = 5,
                            RequestId = 3,
                            ReviewStatus = 1
                        },
                        new
                        {
                            Id = 4,
                            Comment = "خانم تعمیرکار بسیار متخصص و حرفه‌ای بودند. مشکل به سرعت حل شد.",
                            CreatedAt = new DateTime(2025, 12, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = 5,
                            ExpertId = 10,
                            IsDeleted = false,
                            Rating = 5,
                            RequestId = 10,
                            ReviewStatus = 1
                        },
                        new
                        {
                            Id = 5,
                            Comment = "کار خوب بود ولی قیمت کمی بالا بود نسبت به بازار.",
                            CreatedAt = new DateTime(2025, 12, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = 4,
                            ExpertId = 9,
                            IsDeleted = false,
                            Rating = 3,
                            RequestId = 4,
                            ReviewStatus = 0
                        },
                        new
                        {
                            Id = 6,
                            Comment = "متاسفانه کار طبق توافق انجام نشد. از کیفیت راضی نیستم.",
                            CreatedAt = new DateTime(2025, 12, 24, 14, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = 5,
                            ExpertId = 10,
                            IsDeleted = false,
                            Rating = 2,
                            RequestId = 5,
                            ReviewStatus = 2
                        },
                        new
                        {
                            Id = 7,
                            Comment = "به طور کلی راضی هستم. کار خوبی انجام شد و قیمت مناسب بود.",
                            CreatedAt = new DateTime(2025, 12, 24, 19, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = 1,
                            ExpertId = 6,
                            IsDeleted = false,
                            Rating = 4,
                            RequestId = 6,
                            ReviewStatus = 1
                        });
                });

            modelBuilder.Entity("Yarito.Domain.Core.Entities.Users.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int?>("CityId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nchar(11)")
                        .IsFixedLength();

                    b.Property<string>("ProfileImgPath")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<decimal>("WalletBalance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,0)")
                        .HasDefaultValue(0m);

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.ToTable("AppUsers", (string)null);

                    b.HasDiscriminator<string>("UserType").HasValue("AppUser");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Yarito.Domain.Core.Entities.Works.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 12, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "نصب، تعمیر و نگهداری تاسیسات برقی ساختمان",
                            IsDeleted = false,
                            Title = "خدمات برق"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 12, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "نصب، تعمیر و رفع نشتی لوله‌های آب و فاضلاب",
                            IsDeleted = false,
                            Title = "خدمات لوله‌کشی"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 12, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "نظافت منزل، راه پله، پنجره و فرش",
                            IsDeleted = false,
                            Title = "خدمات نظافت"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 12, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "رنگ‌آمیزی داخلی و خارجی ساختمان",
                            IsDeleted = false,
                            Title = "خدمات نقاشی"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 12, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "تعمیر و سرویس انواع لوازم خانگی",
                            IsDeleted = false,
                            Title = "تعمیر لوازم خانگی"
                        });
                });

            modelBuilder.Entity("Yarito.Domain.Core.Entities.Works.Work", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("decimal(18,0)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Works");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BasePrice = 2000000m,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2025, 12, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Title = "سیم‌کشی ساختمان"
                        },
                        new
                        {
                            Id = 2,
                            BasePrice = 500000m,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2025, 12, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Title = "نصب لوستر و چراغ"
                        },
                        new
                        {
                            Id = 3,
                            BasePrice = 300000m,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2025, 12, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Title = "تعمیر کلید و پریز برق"
                        },
                        new
                        {
                            Id = 4,
                            BasePrice = 800000m,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2025, 12, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Title = "تعمیر و رفع نشتی لوله"
                        },
                        new
                        {
                            Id = 5,
                            BasePrice = 400000m,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2025, 12, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Title = "نصب شیر آلات"
                        },
                        new
                        {
                            Id = 6,
                            BasePrice = 600000m,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2025, 12, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Title = "تعمیر توالت فرنگی"
                        },
                        new
                        {
                            Id = 7,
                            BasePrice = 1500000m,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2025, 12, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Title = "نظافت منزل"
                        },
                        new
                        {
                            Id = 8,
                            BasePrice = 700000m,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2025, 12, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Title = "شستشوی پنجره"
                        },
                        new
                        {
                            Id = 9,
                            BasePrice = 2500000m,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2025, 12, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Title = "قالیشویی"
                        },
                        new
                        {
                            Id = 10,
                            BasePrice = 3000000m,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2025, 12, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Title = "نقاشی داخلی ساختمان"
                        },
                        new
                        {
                            Id = 11,
                            BasePrice = 5000000m,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2025, 12, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Title = "نقاشی نمای ساختمان"
                        },
                        new
                        {
                            Id = 12,
                            BasePrice = 2000000m,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2025, 12, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Title = "کاغذ دیواری"
                        },
                        new
                        {
                            Id = 13,
                            BasePrice = 1000000m,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2025, 12, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Title = "تعمیر ماشین لباسشویی"
                        },
                        new
                        {
                            Id = 14,
                            BasePrice = 1200000m,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2025, 12, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Title = "تعمیر یخچال"
                        },
                        new
                        {
                            Id = 15,
                            BasePrice = 1500000m,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2025, 12, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Title = "تعمیر کولر گازی"
                        });
                });

            modelBuilder.Entity("Yarito.Domain.Core.Entities.Users.Customer", b =>
                {
                    b.HasBaseType("Yarito.Domain.Core.Entities.Users.AppUser");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(500)");

                    b.HasDiscriminator().HasValue("Customer");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CityId = 4,
                            CreatedAt = new DateTime(2025, 12, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "ali.mohammadi@example.com",
                            FirstName = "علی",
                            IsDeleted = false,
                            LastName = "محمدی",
                            PhoneNumber = "09121234567",
                            ProfileImgPath = "/images/profiles/customer1.jpg",
                            WalletBalance = 5000000m,
                            Address = "تهران، خیابان ولیعصر، پلاک 123"
                        },
                        new
                        {
                            Id = 2,
                            CityId = 7,
                            CreatedAt = new DateTime(2025, 12, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "zahra.ahmadi@example.com",
                            FirstName = "زهرا",
                            IsDeleted = false,
                            LastName = "احمدی",
                            PhoneNumber = "09131234567",
                            ProfileImgPath = "/images/profiles/customer2.jpg",
                            WalletBalance = 3000000m,
                            Address = "اصفهان، خیابان چهارباغ، پلاک 45"
                        },
                        new
                        {
                            Id = 3,
                            CityId = 10,
                            CreatedAt = new DateTime(2025, 12, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "mohammad.rezaei@example.com",
                            FirstName = "محمد",
                            IsDeleted = false,
                            LastName = "رضایی",
                            PhoneNumber = "09141234567",
                            ProfileImgPath = "/images/profiles/customer3.jpg",
                            WalletBalance = 8000000m,
                            Address = "شیراز، خیابان زند، پلاک 78"
                        },
                        new
                        {
                            Id = 4,
                            CityId = 5,
                            CreatedAt = new DateTime(2025, 12, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "fatemeh.hosseini@example.com",
                            FirstName = "فاطمه",
                            IsDeleted = false,
                            LastName = "حسینی",
                            PhoneNumber = "09151234567",
                            ProfileImgPath = "/images/profiles/customer4.jpg",
                            WalletBalance = 2000000m,
                            Address = "کرج، میدان آزادگان، پلاک 56"
                        },
                        new
                        {
                            Id = 5,
                            CityId = 9,
                            CreatedAt = new DateTime(2025, 12, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "hossein.karimi@example.com",
                            FirstName = "حسین",
                            IsDeleted = false,
                            LastName = "کریمی",
                            PhoneNumber = "09161234567",
                            ProfileImgPath = "/images/profiles/customer5.jpg",
                            WalletBalance = 10000000m,
                            Address = "کاشان، خیابان کمال الملک، پلاک 90"
                        });
                });

            modelBuilder.Entity("Yarito.Domain.Core.Entities.Users.Expert", b =>
                {
                    b.HasBaseType("Yarito.Domain.Core.Entities.Users.AppUser");

                    b.HasDiscriminator().HasValue("Expert");

                    b.HasData(
                        new
                        {
                            Id = 6,
                            CityId = 4,
                            CreatedAt = new DateTime(2025, 12, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "reza.bargkar@example.com",
                            FirstName = "رضا",
                            IsDeleted = false,
                            LastName = "برقکار",
                            PhoneNumber = "09171234567",
                            ProfileImgPath = "/images/profiles/expert1.jpg",
                            WalletBalance = 15000000m
                        },
                        new
                        {
                            Id = 7,
                            CityId = 7,
                            CreatedAt = new DateTime(2025, 12, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "mehdi.loolehkesh@example.com",
                            FirstName = "مهدی",
                            IsDeleted = false,
                            LastName = "لوله‌کش",
                            PhoneNumber = "09181234567",
                            ProfileImgPath = "/images/profiles/expert2.jpg",
                            WalletBalance = 12000000m
                        },
                        new
                        {
                            Id = 8,
                            CityId = 10,
                            CreatedAt = new DateTime(2025, 12, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "sara.nezafatchi@example.com",
                            FirstName = "سارا",
                            IsDeleted = false,
                            LastName = "نظافتچی",
                            PhoneNumber = "09191234567",
                            ProfileImgPath = "/images/profiles/expert3.jpg",
                            WalletBalance = 8000000m
                        },
                        new
                        {
                            Id = 9,
                            CityId = 5,
                            CreatedAt = new DateTime(2025, 12, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "ahmad.naghash@example.com",
                            FirstName = "احمد",
                            IsDeleted = false,
                            LastName = "نقاش",
                            PhoneNumber = "09201234567",
                            ProfileImgPath = "/images/profiles/expert4.jpg",
                            WalletBalance = 20000000m
                        },
                        new
                        {
                            Id = 10,
                            CityId = 4,
                            CreatedAt = new DateTime(2025, 12, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "narges.tamirkar@example.com",
                            FirstName = "نرگس",
                            IsDeleted = false,
                            LastName = "تعمیرکار",
                            PhoneNumber = "09211234567",
                            ProfileImgPath = "/images/profiles/expert5.jpg",
                            WalletBalance = 18000000m
                        });
                });

            modelBuilder.Entity("ExpertWork", b =>
                {
                    b.HasOne("Yarito.Domain.Core.Entities.Users.Expert", null)
                        .WithMany()
                        .HasForeignKey("ExpertsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Yarito.Domain.Core.Entities.Works.Work", null)
                        .WithMany()
                        .HasForeignKey("WorksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Yarito.Domain.Core.Entities.Cities.City", b =>
                {
                    b.HasOne("Yarito.Domain.Core.Entities.Cities.City", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Yarito.Domain.Core.Entities.Images.RequestImage", b =>
                {
                    b.HasOne("Yarito.Domain.Core.Entities.Requests.Request", "Request")
                        .WithMany("RequestImages")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Request");
                });

            modelBuilder.Entity("Yarito.Domain.Core.Entities.Requests.Bid", b =>
                {
                    b.HasOne("Yarito.Domain.Core.Entities.Users.Expert", "Expert")
                        .WithMany("Bids")
                        .HasForeignKey("ExpertId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Yarito.Domain.Core.Entities.Requests.Request", "Request")
                        .WithMany("Bids")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Expert");

                    b.Navigation("Request");
                });

            modelBuilder.Entity("Yarito.Domain.Core.Entities.Requests.Request", b =>
                {
                    b.HasOne("Yarito.Domain.Core.Entities.Requests.Bid", "AcceptedBid")
                        .WithOne()
                        .HasForeignKey("Yarito.Domain.Core.Entities.Requests.Request", "AcceptedBidId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Yarito.Domain.Core.Entities.Users.Customer", "Customer")
                        .WithMany("Requests")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Yarito.Domain.Core.Entities.Works.Work", "Work")
                        .WithMany("Requests")
                        .HasForeignKey("WorkId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AcceptedBid");

                    b.Navigation("Customer");

                    b.Navigation("Work");
                });

            modelBuilder.Entity("Yarito.Domain.Core.Entities.Requests.Review", b =>
                {
                    b.HasOne("Yarito.Domain.Core.Entities.Users.Customer", "Customer")
                        .WithMany("Reviews")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Yarito.Domain.Core.Entities.Users.Expert", "Expert")
                        .WithMany("Reviews")
                        .HasForeignKey("ExpertId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Yarito.Domain.Core.Entities.Requests.Request", "Request")
                        .WithOne("Review")
                        .HasForeignKey("Yarito.Domain.Core.Entities.Requests.Review", "RequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Expert");

                    b.Navigation("Request");
                });

            modelBuilder.Entity("Yarito.Domain.Core.Entities.Users.AppUser", b =>
                {
                    b.HasOne("Yarito.Domain.Core.Entities.Cities.City", "City")
                        .WithMany("Users")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("City");
                });

            modelBuilder.Entity("Yarito.Domain.Core.Entities.Works.Work", b =>
                {
                    b.HasOne("Yarito.Domain.Core.Entities.Works.Category", "Category")
                        .WithMany("Works")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Yarito.Domain.Core.Entities.Cities.City", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Yarito.Domain.Core.Entities.Requests.Request", b =>
                {
                    b.Navigation("Bids");

                    b.Navigation("RequestImages");

                    b.Navigation("Review");
                });

            modelBuilder.Entity("Yarito.Domain.Core.Entities.Works.Category", b =>
                {
                    b.Navigation("Works");
                });

            modelBuilder.Entity("Yarito.Domain.Core.Entities.Works.Work", b =>
                {
                    b.Navigation("Requests");
                });

            modelBuilder.Entity("Yarito.Domain.Core.Entities.Users.Customer", b =>
                {
                    b.Navigation("Requests");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("Yarito.Domain.Core.Entities.Users.Expert", b =>
                {
                    b.Navigation("Bids");

                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
